/* 本地可运行的双语交互网站，无在线运行依赖。 */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], data=window.SITE_DATA;
const en=()=>I18N.lang==='en', t=(zh,eng)=>en()?eng:zh, svgNS='http://www.w3.org/2000/svg';
let currentPeriod='recent', currentIndustry=0, selectedYear=2025;
function svgNode(tag,attrs={},content){const el=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(content!==undefined)el.textContent=content;return el;}
function adoptionReadout(d){$('#adoption-readout').replaceChildren();const b=document.createElement('b'),s=document.createElement('span');b.textContent=`${d.year} · ${d.value}%`;s.textContent=d.year===2025?t('较 2024 年增加 10 个百分点；2025 年 6–7 月调查','Up 10 percentage points from 2024; June–July 2025 survey'):d.year===2024?t('较 2023 年增加 23 个百分点','Up 23 percentage points from 2023'):d.year<2020?t('早期年份口径不同，请结合来源阅读','Early definitions differ; consult the source'):t('该年受访组织中采用 AI 的比例','AI use among respondents’ organizations in that year');$('#adoption-readout').append(b,s);}
function renderAdoption(){
 const values=currentPeriod==='all'?data.adoption:data.adoption.filter(d=>d.year>=2020);
 const yMin=currentPeriod==='all'?20:50,yMax=90;
 const svg=svgNode('svg',{viewBox:'0 0 600 238',role:'group','aria-label':t(`受访组织 AI 使用率趋势，纵轴 ${yMin}%–${yMax}%，非零起点`,`AI-adoption trend; vertical axis ${yMin}%–${yMax}%, non-zero baseline`)});
 svg.append(svgNode('title',{},values.map(d=>`${d.year}: ${d.value}%`).join(', ')));
 const defs=svgNode('defs'),g=svgNode('linearGradient',{id:'area-fill',x1:0,y1:0,x2:0,y2:1});
 g.append(svgNode('stop',{offset:'0%','stop-color':'#79e2c7','stop-opacity':'.23'}),svgNode('stop',{offset:'100%','stop-color':'#79e2c7','stop-opacity':'.01'}));defs.append(g);svg.append(defs);
 const x=i=>45+i*525/(values.length-1),y=v=>205-(v-yMin)/(yMax-yMin)*170;
 for(let v=yMin;v<=yMax;v+=10){svg.append(svgNode('line',{x1:45,y1:y(v),x2:570,y2:y(v),class:'gridline'}),svgNode('text',{x:30,y:y(v)+4,'text-anchor':'end'},v+'%'));}
 const path=values.map((d,i)=>`${i?'L':'M'}${x(i)},${y(d.value)}`).join(' ');
 svg.append(svgNode('path',{d:path+' L570,205 L45,205 Z',fill:'url(#area-fill)'}),svgNode('path',{d:path,fill:'none',stroke:'var(--mint)','stroke-width':3,class:'trend-line','stroke-linecap':'round','stroke-linejoin':'round'}));
 values.forEach((d,i)=>{
  svg.append(svgNode('text',{x:x(i),y:229,'text-anchor':'middle'},d.year));
  const group=svgNode('g',{class:'year-point','data-year':d.year});
  const hit=svgNode('circle',{cx:x(i),cy:y(d.value),r:12,fill:'transparent','aria-hidden':'true',class:'point-hit'});
  const point=svgNode('circle',{cx:x(i),cy:y(d.value),r:4.5,class:'point',tabindex:0,role:'button','aria-label':t(`${d.year} 年采用率 ${d.value}%`,`${d.year}: AI adoption ${d.value}%`)});
  const permanent=i===values.length-1;
  const label=svgNode('text',{x:x(i),y:y(d.value)-14,'text-anchor':'middle',class:'point-value',visibility:permanent?'visible':'hidden','aria-hidden':'true'},d.value+'%');
  const show=()=>label.setAttribute('visibility','visible');
  const hide=()=>{if(!permanent)label.setAttribute('visibility','hidden');};
  const update=()=>{selectedYear=d.year;adoptionReadout(d);};
  group.addEventListener('mouseenter',show);group.addEventListener('mouseleave',hide);
  point.addEventListener('focus',show);point.addEventListener('blur',()=>{if(!permanent)label.setAttribute('visibility','hidden');});
  point.addEventListener('click',update);
  point.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();update();}});
  group.append(hit,point,label);svg.append(group);
 });
 $('#adoption-chart').replaceChildren(svg);
 $('#adoption-axis-note').textContent=t(`纵轴 ${yMin}%–${yMax}%，非零起点，用于观察变化。`,`Vertical axis: ${yMin}%–${yMax}%; a non-zero baseline highlights changes.`);
 adoptionReadout(values.find(d=>d.year===selectedYear)||values.at(-1));
}
$$('[data-period]').forEach(btn=>btn.addEventListener('click',()=>{currentPeriod=btn.dataset.period;$$('[data-period]').forEach(b=>{b.classList.toggle('selected',b===btn);b.setAttribute('aria-pressed',String(b===btn));});renderAdoption();}));
const industryPanel=$('.industry-panel');industryPanel.id='industry-content';industryPanel.setAttribute('role','tabpanel');
function createIndustryTabs(){const tabs=$('.industry-tabs');tabs.replaceChildren();data.industries.forEach((item,index)=>{const b=document.createElement('button');b.textContent=en()?data.industriesEn[index].name:item.name;b.setAttribute('role','tab');b.id=`industry-tab-${index}`;b.setAttribute('aria-controls','industry-content');b.setAttribute('aria-selected',String(index===currentIndustry));b.tabIndex=index===currentIndustry?0:-1;b.addEventListener('click',()=>selectIndustry(index));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(index+1)%data.industries.length;if(e.key==='ArrowLeft')next=(index+data.industries.length-1)%data.industries.length;if(e.key==='Home')next=0;if(e.key==='End')next=data.industries.length-1;if(next!==undefined){e.preventDefault();selectIndustry(next);$(`#industry-tab-${next}`).focus();}});tabs.append(b);});}
function selectIndustry(index){currentIndustry=index;const original=data.industries[index],item=en()?{...original,...data.industriesEn[index]}:original;$$('.industry-tabs button').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1;});industryPanel.setAttribute('aria-labelledby',`industry-tab-${index}`);['tag','title','description','symbol','value','limit'].forEach(key=>$(`#industry-${key}`).textContent=item[key]);$('#industry-flow').replaceChildren();item.steps.forEach(([title,desc],i)=>{const card=document.createElement('div'),small=document.createElement('small'),h=document.createElement('h4'),p=document.createElement('p');small.textContent=(en()?['01 / DATA','02 / INTELLIGENCE','03 / ACTION','04 / VALUE']:['01 / 数据','02 / 智能','03 / 行动','04 / 价值'])[i];h.textContent=title;p.textContent=desc;card.append(small,h,p);$('#industry-flow').append(card);});renderCase(index);}
function renderCase(index){const original=data.caseStudies[index],item=en()?{...original,...original.en}:original,container=$('#industry-case');container.replaceChildren();const heading=document.createElement('div'),label=document.createElement('small'),h=document.createElement('h4'),link=document.createElement('a');label.textContent=t('真实案例 / 证据','REAL CASE / EVIDENCE');link.href=item.url;link.target='_blank';link.rel='noopener';link.textContent=item.title;h.append(link);heading.append(label,h);const metric=document.createElement('div');metric.className='case-metric';const strong=document.createElement('strong'),m=document.createElement('span');strong.textContent=item.metric;m.textContent=item.metricLabel;metric.append(strong,m);const body=document.createElement('p');body.textContent=item.body;const scope=document.createElement('p');scope.className='case-scope';scope.textContent=t('范围与限制：','Scope and limitations: ')+item.scope;const source=document.createElement('a');source.className='case-source';source.href=item.url;source.target='_blank';source.rel='noopener';source.textContent=t('查看原始论文 / 报告：','Open original paper / report: ')+(en()?item.source.replace('等','et al.').replace('新闻公告','news release').replace('官方报告','official report').replace('修订稿','revised paper'):item.source);container.append(heading,metric,body,scope,source);}
function updateSimulation(){const coverage=Number($('#coverage').value)/100,saving=Number($('#saving').value)/100,review=Number($('#review').value)/100;['coverage','saving','review'].forEach(id=>$(`#${id}-output`).textContent=$(`#${id}`).value+'%');const manual=100*(1-coverage),assisted=100*coverage*(1-saving),checking=100*coverage*review,total=manual+assisted+checking,net=100-total,gain=(100/total-1)*100,fmt=n=>Number(n.toFixed(1)).toString();$('#total-time').textContent=fmt(total);$('#saving-result').textContent=net>=0?t(`节省 ${fmt(net)} 小时`,`${fmt(net)} hours saved`):t(`增加 ${fmt(-net)} 小时`,`${fmt(-net)} extra hours`);$('#productivity-result').textContent=t(`理论吞吐量${gain>=0?'提升':'下降'} ${Math.abs(gain).toFixed(1)}%`,`Theoretical throughput ${gain>=0?'gain':'loss'}: ${Math.abs(gain).toFixed(1)}%`);$('#sim-bar').replaceChildren();[['manual',manual,t('人工','Manual')],['assisted',assisted,t('辅助','Assisted')],['review',checking,t('复核','Review')]].forEach(([cls,value,label])=>{if(value<=0)return;const i=document.createElement('i');i.className=cls;i.style.width=value/130*100+'%';i.textContent=value>=7?fmt(value)+'h':'';i.title=`${label}: ${fmt(value)}h`;$('#sim-bar').append(i);});$('#sim-bar').setAttribute('aria-label',t(`人工 ${fmt(manual)} 小时，AI 辅助 ${fmt(assisted)} 小时，复核 ${fmt(checking)} 小时，总计 ${fmt(total)} 小时`,`Manual ${fmt(manual)}h; AI-assisted ${fmt(assisted)}h; review ${fmt(checking)}h; total ${fmt(total)}h`));$('#sim-insight').textContent=coverage===0?t('尚未采用 AI：任务保持 100 小时。提高任务覆盖率，观察各部分如何变化。','Without AI, the workload remains 100 hours. Increase coverage to see how the components change.'):net>0?t('协同收益来自节省的时间超过复核投入。继续调整参数，观察效率提升与质量保障之间的平衡。','Collaboration pays off when time saved exceeds review effort. Adjust parameters to explore the balance between efficiency and quality assurance.'):net<0?t('复核成本超过节省的时间，流程反而变慢。采用 AI 的前提是任务适配，并控制核验与返工成本。','Review costs exceed time saved, making the workflow slower. AI needs suitable tasks and manageable verification and rework costs.'):t('节省的时间与复核投入相抵，净收益为零。更高的采用率并不自动带来更高效率。','Time saved equals review effort, so the net gain is zero. Higher adoption does not automatically improve efficiency.');}
$$('.controls input').forEach(el=>el.addEventListener('input',updateSimulation));const presets={balanced:[60,40,10],high:[80,60,8],risk:[80,20,35]};function setParams(values){['coverage','saving','review'].forEach((id,i)=>$('#'+id).value=values[i]);updateSimulation();}$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>setParams(presets[b.dataset.preset])));$('#reset').addEventListener('click',()=>setParams(presets.balanced));
function renderSources(){$('#source-list').replaceChildren();data.sources.forEach((source,i)=>{const row=document.createElement('div');row.className='source-row';const index=document.createElement('span');index.textContent=String(i+1).padStart(2,'0');const content=document.createElement('div'),title=document.createElement('h3'),titleLink=document.createElement('a'),p=document.createElement('p'),a=document.createElement('a');titleLink.textContent=en()?(source.enTitle||source.title):source.title;titleLink.href=source.url;titleLink.target='_blank';titleLink.rel='noopener';title.append(titleLink);p.textContent=en()?source.enUse:source.use;a.textContent=(en()?(source.enOrg||source.org):source.org)+' / '+source.year;a.href=source.url;a.target='_blank';a.rel='noopener';content.append(title,p);row.append(index,content,a);$('#source-list').append(row);});}
const themeButton=$('#theme');function applyTheme(light){document.body.classList.toggle('light',light);themeButton.setAttribute('aria-label',light?t('切换为深色主题','Switch to dark mode'):t('切换为浅色主题','Switch to light mode'));themeButton.title=themeButton.getAttribute('aria-label');themeButton.textContent=light?'☾':'☼';try{localStorage.setItem('ai-theme',light?'light':'dark');}catch{}}let light=false;try{light=localStorage.getItem('ai-theme')==='light';}catch{}applyTheme(light);themeButton.addEventListener('click',()=>applyTheme(!document.body.classList.contains('light')));
function renderLanguage(){renderAdoption();createIndustryTabs();selectIndustry(currentIndustry);updateSimulation();renderSources();applyTheme(document.body.classList.contains('light'));}window.addEventListener('languagechange',renderLanguage);renderLanguage();
const sections=$$('main>.section'),navLinks=$$('.sidebar nav a');function updateNav(){let current=sections[0];for(const section of sections){if(section.getBoundingClientRect().top<=window.innerHeight*.33)current=section;}navLinks.forEach(a=>{const active=a.getAttribute('href')==='#'+current.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}let scheduled=false;window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(()=>{updateNav();scheduled=false;});}},{passive:true});updateNav();
