/* 每个行业的案例与原始证据；企业披露、随机实验与开放数据库分别标注。 */
window.SITE_DATA.caseStudies=[
 {title:'西门子安贝格工厂：预测 PCB 质量',metric:'−30%',metricLabel:'X 射线检测工作量',body:'西门子 2022 年披露，安贝格工厂用生产过程数据预测电路板质量，减少不必要的 X 射线检测。AI 被嵌入边缘设备，参与生产现场的闭环优化。',scope:'企业官方案例披露，减少的是检测工作量；不等同于总生产率提升 30%，也不是独立随机实验。',source:'Siemens Industrial Edge · 2022',url:'https://blog.siemens.com/2022/04/ready-for-tomorrows-ai-siemens-industrial-edge/',en:{title:'Siemens Amberg: predicting PCB quality',metricLabel:'less X-ray testing effort',body:'Siemens reported in 2022 that its Amberg factory used production data to predict circuit-board quality and avoid unnecessary X-ray tests. An edge application brought the model into the production feedback loop.',scope:'Company-reported case. The metric is testing effort, not a 30% increase in overall productivity; this was not an independent randomized trial.'}},
 {title:'John Deere See & Spray：识别杂草后精准喷药',metric:'−59%',metricLabel:'平均除草剂用量（企业披露）',body:'John Deere 的视觉识别系统区分作物与杂草，按需控制喷嘴。企业 2024 年公告报告，在美国玉米、大豆、棉花田应用中平均节省 59% 的除草剂用量。',scope:'2024 生长季、超过 100 万英亩作业的企业估计，节省相对于全田喷施；取决于田间杂草压力、作物与设置，不能直接推导增产效果。',source:'John Deere · 2024 新闻公告',url:'https://www.deere.ca/en/news/all-news/see-spray-herbicide-savings/',en:{title:'John Deere See & Spray: targeting weeds',metricLabel:'average herbicide savings (company report)',body:'Computer vision distinguishes weeds from crops and activates individual nozzles. John Deere reported average herbicide savings of 59% across US corn, soybean and cotton fields in the 2024 season.',scope:'Company estimate covering more than one million acres treated in 2024, relative to broadcast spraying. Savings depend on weed pressure, crop and settings; they do not establish an increase in crop yield.'}},
 {title:'瑞典 MASAI 试验：AI 辅助乳腺筛查',metric:'−44.3%',metricLabel:'筛查阅片工作量',body:'2023 年发表于 The Lancet Oncology 的 MASAI 随机试验纳入 80,033 名参与者。AI 用于风险分流与检测辅助，使阅片工作量减少 44.3%。',scope:'该数字来自试验的初期安全分析，比较 AI 辅助流程与常规双人阅片；不表示所有诊疗工作量下降，也不意味着可以取消医生复核。',source:'Lång 等 · The Lancet Oncology · 2023',url:'https://doi.org/10.1016/S1470-2045(23)00298-X',en:{title:'Sweden’s MASAI trial: AI-supported screening',metricLabel:'less screen-reading workload',body:'The MASAI randomized trial, published in The Lancet Oncology in 2023, enrolled 80,033 participants. AI supported risk triage and detection, reducing screen-reading workload by 44.3%.',scope:'This result is from the initial clinical safety analysis, comparing an AI-supported workflow with standard double reading. It does not cover all clinical work or remove the need for physician review.'}},
 {title:'AlphaFold 数据库：开放蛋白质结构预测',metric:'2 亿+',metricLabel:'蛋白质结构预测（2022 年发布）',body:'2022 年 7 月，DeepMind 与 EMBL-EBI 将 AlphaFold 数据库扩展至超过 2 亿条蛋白质结构预测，使研究者能够先检索模型，再设计验证实验。',scope:'衡量的是预测结构的覆盖规模，不是 2 亿项经过实验确认的发现；预测置信度、结构状态和适用范围仍需评估。',source:'EMBL-EBI · 2022 官方报告',url:'https://www.ebi.ac.uk/about/news/technology-and-innovation/alphafold-200-million/',en:{title:'AlphaFold: open protein-structure predictions',metric:'200M+',metricLabel:'protein-structure predictions (2022 release)',body:'In July 2022, DeepMind and EMBL-EBI expanded the AlphaFold database to more than 200 million protein-structure predictions, letting researchers consult models before designing validation experiments.',scope:'This is the scale of predicted structures, not 200 million experimentally confirmed discoveries. Confidence, structural states and fitness for a particular use still require evaluation.'}},
 {title:'客服 AI 助手：让新手更快掌握经验',metric:'+35%',metricLabel:'新手及低技能组每小时解决问题数',body:'NBER 2023 年修订工作论文研究 5,179 名客服人员。AI 给出回答建议并传播优秀工作者经验；平均产出提升 14%，新手及低技能组提升 35%。',scope:'采用 2023 年 10 月工作论文版本；特定企业的现场研究，不代表全部知识工作，也不应与其他版本的估计混用。',source:'Brynjolfsson 等 · NBER · 2023 修订稿',url:'https://www.nber.org/system/files/working_papers/w31161/revisions/w31161.rev1.pdf',en:{title:'An AI assistant helps novice support agents',metricLabel:'more issues resolved per hour: novice / low-skill group',body:'The revised 2023 NBER working paper studied 5,179 customer-support agents. AI recommendations helped spread experienced workers’ practices. Average output rose 14%, with a 35% increase for novice and low-skill agents.',scope:'October 2023 working-paper version; a field study in a specific firm. It does not represent all knowledge work, and estimates from different versions should not be mixed.'}}
];
window.SITE_DATA.industriesEn=[
 {name:'Manufacturing',tag:'MANUFACTURING',title:'From execution to a sensing production line.',description:'Turn equipment signals into actionable judgments, linking inspection, maintenance and scheduling in a feedback loop.',steps:[['Equipment and images','Collect sensor signals, product images and past failure records.'],['Detection and prediction','Identify anomalies and suggest inspection or maintenance actions.'],['Human–AI decisions','Engineers validate alerts and adjust maintenance and production plans.'],['Quality and resource efficiency','Reduce unnecessary processing and improve process control.']],value:'Production tools become systems that sense conditions and provide feedback.',limit:'Reliable sensors, representative data and engineering review of false alerts and missed defects.'},
 {name:'Agriculture',tag:'AGRICULTURE',title:'Make each input fit what the land needs.',description:'Combine local experience with environmental and crop data for more precise farm management.',steps:[['Field observations','Collect soil, weather and crop-image data.'],['State analysis','Detect signs of pests and disease; estimate water and nutrient needs.'],['Agronomic decisions','Use local expertise to plan irrigation and crop protection.'],['Precise resource allocation','Avoid unnecessary inputs and support stable production.']],value:'Better visibility into crops supports locally tailored resource allocation.',limit:'Local crop validation, equipment coverage and robustness in extreme weather.'},
 {name:'Healthcare',tag:'HEALTHCARE',title:'Bring useful evidence to professional decisions.',description:'AI can organize information and flag image findings to support clinical work.',steps:[['Authorized clinical data','Process images and clinical records within approved access.'],['Assisted analysis','Identify candidate abnormalities and verifiable findings.'],['Physician review','Combine patient history and examination results in professional judgment.'],['Service capacity','Support triage and follow-up to improve access to care.']],value:'Help professionals handle complex information and extend service capacity.',limit:'Clinical validation, privacy safeguards, bias assessment and physician responsibility.'},
 {name:'Science',tag:'SCIENCE',title:'Expand exploration beyond conventional trial and error.',description:'Models screen candidates so researchers can focus experimental resources on promising questions.',steps:[['Research data','Combine measurements, literature and structural information.'],['Candidate screening','Predict properties and propose testable hypotheses.'],['Experimental validation','Researchers test predictions and revise the models.'],['Knowledge and innovation','Shorten exploration cycles and uncover candidate materials or methods.']],value:'Data and models expand the objects of research and change how knowledge is produced.',limit:'Experimental validation, reproducibility and sufficient training-data coverage.'},
 {name:'Knowledge services',tag:'KNOWLEDGE WORK',title:'Make knowledge a partner in everyday work.',description:'Embed retrieval, drafting and organization into workflows, leaving more time for judgment and communication.',steps:[['Knowledge and needs','Connect authorized knowledge bases with user questions.'],['Retrieval and generation','Provide relevant material, drafts and traceable evidence.'],['Human editing and review','Check facts, improve communication and handle exceptions.'],['Experience diffusion','Help novices learn workflows and improve service efficiency.']],value:'Share practical knowledge at lower cost and reshape learning and collaboration.',limit:'Fact checking, copyright boundaries, confidential-data protection and ongoing quality review.'}
];
const extraSources=[
 ['Ready for Tomorrow’s AI – Siemens Industrial Edge','Siemens','2022','安贝格工厂：AI 预测 PCB 质量，X 射线检测工作量减少 30%。','Amberg factory: 30% less X-ray testing effort using AI quality prediction.',0],
 ['See & Spray Customers See 59% Average Herbicide Savings in 2024','John Deere','2024','2024 年精准喷施案例：企业披露平均除草剂节省 59%。','2024 targeted-spraying case: company-reported average herbicide savings of 59%.',1],
 ['AI-supported screen reading in the MASAI trial: a clinical safety analysis','The Lancet Oncology','2023','MASAI 随机试验初期分析：筛查阅片工作量下降 44.3%。','Initial MASAI randomized-trial analysis: 44.3% less screen-reading workload.',2],
 ['AlphaFold predicts structure of almost every catalogued protein known to science','EMBL-EBI','2022','2022 年 AlphaFold 数据库发布超过 2 亿条预测结构。','The 2022 AlphaFold database release exceeded 200 million predicted structures.',3]
];
extraSources.forEach(([title,org,year,use,enUse,index])=>window.SITE_DATA.sources.push({title,org,year,use,enUse,url:window.SITE_DATA.caseStudies[index].url}));
['AI use was 78% in 2024 and 55% in 2023; a fixed report snapshot.','2017–2024 organizational AI-use series; 2024 uses the July survey value of 78%.','October 2023 revised working paper: output +14% on average; +35% for novice / low-skill agents.','Specific professional writing tasks: time −40%; rated quality +18%.','A specified JavaScript HTTP-server task: completion time −55.8%.','Theory of new quality productive forces: innovation, factor coordination and industrial transformation.'].forEach((text,i)=>window.SITE_DATA.sources[i].enUse=text);
window.SITE_DATA.sources[5].enTitle='Developing new quality productive forces for high-quality development';
window.SITE_DATA.sources[5].enOrg='NDRC';
window.SITE_DATA.sources[2].enOrg='NBER · Brynjolfsson et al.';
window.SITE_DATA.sources[4].enOrg='Peng et al.';
