/* 真实研究数据与定性场景分开保存；来源均通过网页链接查阅。 */
window.SITE_DATA={
 adoption:[{year:2017,value:20},{year:2018,value:47},{year:2019,value:58},{year:2020,value:50},{year:2021,value:56},{year:2022,value:50},{year:2023,value:55},{year:2024,value:78},{year:2025,value:88}],
 industries:[
 {name:'智能制造',tag:'MANUFACTURING / 制造',title:'让生产线，从执行走向感知。',description:'把设备信号转化为可行动的判断，使质量检测、维护与排产形成反馈闭环。',symbol:'[01]',steps:[['设备与图像','采集传感器信号、产品图像与历史故障记录。'],['识别与预测','模型识别异常，提供缺陷判断与维护建议。'],['人机协同决策','工程师验证预警，调整维护和生产计划。'],['质量与资源效率','减少无效加工，提升生产过程的可控性。']],value:'劳动资料由被动工具升级为可感知、可反馈的生产系统。',limit:'可靠传感器、代表性训练数据，以及工程师对误报漏报的复核。'},
 {name:'智慧农业',tag:'AGRICULTURE / 农业',title:'让每一份投入，更贴近土地需要。',description:'以环境和作物数据辅助农事决策，让经验与精细化管理相结合。',symbol:'[02]',steps:[['田间观测','获取土壤、气象与作物影像数据。'],['状态分析','识别病虫害迹象，估计水肥需求。'],['农技人员决策','结合本地农艺知识安排灌溉与防治。'],['精细资源配置','减少不必要投入，支持稳定生产。']],value:'劳动对象的信息更可见，资源配置从统一投入走向因地施策。',limit:'本地作物验证、设备覆盖与极端天气下的稳健性。'},
 {name:'医疗健康',tag:'HEALTHCARE / 医疗',title:'让专业知识，更及时地辅助判断。',description:'AI 可以辅助整理信息和识别影像线索，支持医护人员开展工作。',symbol:'[03]',steps:[['合规医疗数据','在授权范围内处理影像和临床记录。'],['辅助分析','识别候选异常，整理可核验的线索。'],['医生复核','结合病史与检查结果作出专业判断。'],['服务能力提升','为分诊与随访提供辅助，支持服务可及性。']],value:'增强专业劳动者处理复杂信息的能力，为更多人提供服务。',limit:'临床验证、隐私保护、偏差评估与医生承担最终诊疗责任。'},
 {name:'科学研究',tag:'SCIENCE / 科研',title:'让探索空间，超越传统试错。',description:'模型帮助筛选候选方案，让研究者把实验资源集中到更有价值的问题。',symbol:'[04]',steps:[['研究数据','整合实验测量、文献与结构信息。'],['候选方案筛选','用模型预测性质、提出可验证假设。'],['实验检验','研究者设计实验，验证并修正预测。'],['知识与技术创新','缩短探索循环，发现潜在新材料与新方法。']],value:'劳动对象拓展到数据和模型，推动知识生产方式改变。',limit:'预测必须接受实验检验，关注可重复性与训练数据覆盖。'},
 {name:'知识服务',tag:'KNOWLEDGE WORK / 服务',title:'让知识成为每个人的工作伙伴。',description:'将检索、草拟和整理嵌入工作流，把更多时间留给专业判断与交流。',symbol:'[05]',steps:[['知识与问题','连接授权知识库与用户需求。'],['检索与生成','给出相关资料、初稿和可追溯的线索。'],['人工编辑复核','核验事实、完善表达并处理例外。'],['经验的扩散','帮助新手掌握流程，提高知识服务效率。']],value:'知识经验以低成本传播，改变学习与协作方式。',limit:'事实核验、版权边界、机密信息保护与持续质量评估。'}],
 sources:[
 {title:'The AI Index Report 2025',org:'Stanford HAI',year:'2025',use:'2024 年 AI 使用率 78%，2023 年 55%；固定报告快照。',url:'https://hai.stanford.edu/ai-index/2025-ai-index-report'},
 {title:'The state of AI: How organizations are rewiring to capture value',org:'McKinsey',year:'2025',use:'组织 AI 使用率 2017–2024 年序列；2024 采用 7 月调查值 78%。',url:'https://www.mckinsey.com/~/media/mckinsey/business%20functions/quantumblack/our%20insights/the%20state%20of%20ai/2025/the-state-of-ai-how-organizations-are-rewiring-to-capture-value_final.pdf'},
 {title:'Generative AI at Work',org:'NBER · Brynjolfsson 等',year:'2023',use:'2023 年 10 月修订工作论文：客服产出平均 +14%；新手及低技能组 +35%。',url:'https://www.nber.org/system/files/working_papers/w31161/revisions/w31161.rev1.pdf'},
 {title:'Experimental evidence on the productivity effects of generative artificial intelligence',org:'Science · Noy & Zhang',year:'2023',use:'特定专业写作任务：平均用时 −40%，评审质量 +18%。',url:'https://doi.org/10.1126/science.adh2586'},
 {title:'The Impact of AI on Developer Productivity: Evidence from GitHub Copilot',org:'Peng 等',year:'2023',use:'指定 JavaScript HTTP 服务器任务：完成用时 −55.8%。',url:'https://arxiv.org/abs/2302.06590'},
 {title:'发展新质生产力是推动高质量发展的内在要求和重要着力点',org:'国家发展和改革委员会',year:'2024',use:'新质生产力理论背景：创新、生产要素优化组合与产业转型。',url:'https://www.ndrc.gov.cn/xwdt/ztzl/NEW_srxxgcjjpjjsx/jjsxyjqk/sxlt/202404/t20240412_1365653.html'},
 {title:'The state of AI in 2025: Agents, innovation, and transformation',enTitle:'The state of AI in 2025: Agents, innovation, and transformation',org:'McKinsey',enOrg:'McKinsey',year:'2025',use:'2025 年 AI 使用率 88%；6 月 25 日至 7 月 29 日调查，1,993 名受访者、105 个国家。衡量至少一个业务职能经常使用 AI，样本不代表所有组织。',enUse:'2025 AI use: 88%. Survey conducted June 25–July 29, with 1,993 respondents in 105 countries. Measures regular use in at least one business function; the sample does not represent all organizations.',url:'https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai-2025'}]
};
