/* 静态正文逐节点翻译；动态内容由 app.js 随语言状态重新呈现。 */
window.I18N={lang:'zh',staticText:{
 '较 2024 年上升':'Up from 2024 by','10 个百分点':'10 percentage points','McKinsey 2025 · 受访组织':'McKinsey 2025 · Respondents’ organizations','2025 为 6–7 月调查，1,993 名受访者、105 个国家；2024 为 7 月调查。不同年份样本不同，2017–2019 定义有所变化。':'2025: June–July survey, 1,993 respondents in 105 countries. 2024: July survey. Samples vary by year; definitions differed in 2017–2019.',
 '跳到主要内容':'Skip to main content','智变':'Intelligence in Motion','智变 / AI OBSERVATORY':'AI PRODUCTIVITY OBSERVATORY','探索新质生产力':'EXPLORE PRODUCTIVITY','全景观察':'Overview','效率的证据':'Evidence','产业变革图谱':'Industry atlas','人机协同实验室':'Collaboration lab','机遇与边界':'Opportunities & limits','数据与方法':'Data & methods',
 '技术的价值，':'The value of technology','在于创造新的可能。':'lies in new possibilities.','可视化导论 · 课程项目':'Introduction to Visualization · Course project','研究快照 / 2026版报告':'Research snapshot / 2026 edition',
 '人工智能 × 新质生产力':'AI × New Quality Productive Forces','从技术突破，到生产力跃迁':'FROM TECHNICAL BREAKTHROUGHS TO PRODUCTIVITY','当 AI 成为':'When AI becomes','新的生产力。':'a new productive force.','更快的工作，只是开始。':'Faster work is only the beginning.','用数据观察人工智能如何重塑劳动、连接产业、释放创新。':'Explore how AI reshapes work, connects industries and enables innovation.',
 '观察命题 / 01':'OBSERVATION / 01','AI 的意义，不只在于替代重复劳动，':'AI can do more than automate routine tasks.','更在于拓展人的能力与生产的边界。':'It can extend human capability and the boundaries of production.','进入人机协同实验室':'Explore the collaboration lab',
 '组织 AI 使用率':'Organizations using AI','客服工作生产率':'Customer-support productivity','专业写作任务用时':'Professional writing task time','实地研究':'Field study','随机实验':'Randomized trial','较 2023 年上升':'Up from 2023 by','23 个百分点':'23 percentage points','AI 辅助下，每小时解决更多问题':'More issues resolved per hour with AI support','同时，输出质量平均提升':'Average output quality also increased by','Stanford AI Index 2025 · 受访组织':'Stanford AI Index 2025 · Survey respondents','NBER 2023 工作论文版本':'NBER 2023 working-paper version',
 '从试点，走向普及':'From pilots to widespread use','真实调查':'Survey data','受访组织使用 AI 的比例':'Share of respondents’ organizations using AI','全部年份':'All years','AI 开始从单点工具进入组织流程':'AI is moving from individual tools into organizational workflows','来源：':'Sources:','McKinsey 全球 AI 调查':'McKinsey Global AI Surveys','Stanford AI Index 2025。':'Stanford AI Index 2025.','2024 为 7 月调查；不同年份样本不同，2017–2019 定义有所变化。':'2024 refers to the July survey. Samples vary by year; definitions differed in 2017–2019.','查看口径':'Read methodology',
 '生产力的三个支点':'Three pillars of productivity','概念图':'Concept diagram','劳动者':'Workers','劳动资料':'Production tools','劳动对象':'Objects of work','协同引擎':'Collaboration','人的能力增强':'Human capability','工具智能升级':'Intelligent tools','数据成为要素':'Data as a factor','三类要素的优化组合，推动效率与质量共同提升。此图为理论阐释，不表示量化贡献。':'Coordinating these factors can improve efficiency and quality. This diagram explains a concept, not measured contributions.','理论来源：国家发展改革委':'Theory source: NDRC','核心洞察':'KEY INSIGHT','从“更多投入”到“更好组合”——AI 让知识、数据与人的创造力形成新的协作方式。':'From more inputs to better coordination: AI connects knowledge, data and human creativity in new ways.',
 '效率提升，有迹可循。':'Evidence of efficiency gains.','观察不同任务中的研究结果，而非把一个数字推广到所有行业。':'Read results in their task context; one estimate does not describe every industry.','01 / 客户服务':'01 / CUSTOMER SUPPORT','02 / 专业写作':'02 / PROFESSIONAL WRITING','03 / 软件开发':'03 / SOFTWARE DEVELOPMENT','知识经验的加速传递':'Faster transfer of practical knowledge','更少时间，更好表达':'Less time, better communication','让想法更快成为原型':'Turn ideas into prototypes sooner','每小时解决问题数的平均提升':'Average increase in issues resolved per hour','完成写作任务的平均用时下降':'Average reduction in writing-task time','指定编程任务的完成用时下降':'Reduction in time for a specified coding task','无 AI 辅助':'Without AI','有 AI 辅助':'With AI',
 '客服现场研究表明，AI 能把优秀工作者的经验传递给新人；新手及低技能组收益更明显。':'The field study suggests that AI helps novices adopt experienced workers’ practices, with larger gains for novice and low-skill agents.','AI 可承担草拟与改写，人则把更多注意力投入判断、结构与事实核验。':'AI can assist drafting and revision, leaving more attention for judgment, structure and fact checking.','在构建 JavaScript HTTP 服务器的实验中，AI 辅助让开发者更快完成任务。':'In an experiment building a JavaScript HTTP server, AI-assisted developers completed the task sooner.',
 '研究范围与限制':'Scope and limitations','5,179 名客服人员；指标为每小时解决的问题数。引用 2023 工作论文版本（平均 14%，新手及低技能组 35%）。来自特定企业，不能直接外推到所有岗位。':'5,179 support agents; the outcome is issues resolved per hour. The 2023 working-paper version reports 14% on average and 35% for novice / low-skill agents. A specific firm; not a universal estimate.','453 名受过大学教育的专业人士，完成特定写作任务。随机实验中用时下降 40%，评审质量提升 18%。不代表长篇创作或所有专业任务。':'453 college-educated professionals completed specified writing tasks. The randomized trial found 40% less time and 18% higher rated quality. It does not cover all writing or professional tasks.','95 名开发者参与的受控实验，使用 GitHub Copilot。结果衡量单一编程任务，不代表项目整体交付速度、维护成本或代码安全。':'A controlled experiment with 95 developers using GitHub Copilot. It measures one coding task, not total project delivery, maintenance costs or code security.','NBER · 2023 工作论文':'NBER · 2023 working paper','Peng 等 · 2023':'Peng et al. · 2023','图表将各研究的无 AI 组设为 100。客服图表示产出，写作与编程图表示用时；不同指标不能直接排名或求平均。':'Each study’s non-AI group is normalized to 100. Support measures output; writing and coding measure time. These outcomes should not be ranked or averaged together.',
 '改变一个环节，连接整个产业。':'Change a step. Connect an industry.','选择行业，沿着“数据—智能—行动—价值”理解转型机制。':'Choose an industry and follow the path from data to intelligence, action and value.','场景机制 + 真实案例':'Mechanisms + real cases','生产力跃迁':'PRODUCTIVITY MECHANISM','落地前提':'IMPLEMENTATION CONDITIONS',
 '把“人机协同”变成一次实验。':'Experiment with human–AI collaboration.','当采用率提高，节省的时间一定更多吗？试着把复核成本也算进去。':'Does higher adoption always save more time? Include the cost of human review.','教学模拟 · 非预测':'Teaching simulation · Not a forecast','配置你的工作流程':'Configure a workflow','以完成一批任务需要 100 小时为基线。':'Baseline: 100 hours to complete a fixed batch of tasks.','AI 可辅助的任务占比':'Share of tasks AI can assist','辅助任务的用时节省率':'Time saved on assisted tasks','复核成本 / 基线任务用时':'Review cost / baseline task time','平衡协同':'Balanced','高效辅助':'Efficient assistance','高复核成本':'High review cost','恢复默认参数':'Reset parameters','相同任务，需要多少时间？':'How long does the same work take?','基线 100 小时':'Baseline: 100 hours','小时':'hours','传统流程':'Traditional','人机协同':'Human + AI','人工处理':'Manual work','AI 辅助处理':'AI-assisted work','人工复核':'Human review','查看计算方法':'Calculation method',
 '人工处理 = 100 × (1 − 占比)':'Manual work = 100 × (1 − share)','AI 辅助处理 = 100 × 占比 × (1 − 节省率)':'Assisted work = 100 × share × (1 − saving rate)','复核 = 100 × 占比 × 复核成本率':'Review = 100 × share × review-cost rate','总用时 = 三部分相加；理论吞吐量提升 = 100 ÷ 总用时 − 1。':'Total time = the three components combined; theoretical throughput gain = 100 ÷ total time − 1.','假定任务规模与质量目标不变，不包含培训、系统集成与硬件成本。参数为教学假设，不是行业测量数据。':'Assumes a fixed workload and quality target; excludes training, integration and hardware costs. Parameters are teaching assumptions, not measured industry data.',
 '生产力的下一步，也关乎人。':'The next step in productivity is also about people.','技术能力转化为社会价值，需要技能、制度与责任共同进步。':'Skills, institutions and responsibility must evolve to turn technical capability into social value.','从替代任务，到增强能力':'From automating tasks to enhancing capability','重复劳动可以交给工具；目标设定、价值判断与责任承担仍需要人。职业转型也需要培训和支持。':'Tools can handle routine work. People still set goals, make value judgments and bear responsibility. Career transitions also need training and support.','从数据积累，到可信应用':'From more data to trusted applications','高质量数据、隐私保护与结果复核，是可靠应用的基础。错误输出与偏差会侵蚀效率收益。':'Quality data, privacy safeguards and review underpin reliable applications. Errors and bias can erase efficiency gains.','从局部提速，到系统创新':'From local speed gains to system innovation','生产流程与组织方式同步改进，才能把单点效率转化为新产品、新模式与更高质量的供给。':'Changes to workflows and organizations help turn task-level gains into new products, new models and better output.',
 '让智能参与生产，':'Bring intelligence into production.','让人定义未来。':'Let people define the future.','AI 的潜力来自技术突破，AI 的价值实现于人的创造与协作。':'AI’s potential comes from technical progress; its value is realized through human creativity and collaboration.','回到全景观察':'Back to overview','每一个数字，都有出处。':'Every number has a source.','本项目为固定研究快照，引用 2022–2025 年案例、研究与报告，不代表 2026 年实时数据。':'A fixed snapshot of cases, studies and reports from 2022–2025, not live 2026 data.','如何阅读这个网站':'How to read this site','真实数据：':'Evidence:','组织采用率、任务研究和行业案例；企业披露均单独标注。':'Adoption surveys, task studies and industry cases; company claims are explicitly labeled.','定性阐释：':'Concepts:','生产要素概念图与行业流程。':'The factor diagram and industry workflows.','教学模拟：':'Simulation:','实验室的所有参数和计算结果。':'All lab parameters and calculated results.','各研究的样本、指标与实验条件不同。任务效率提升不等于宏观经济增速，也不等于已证明的全要素生产率提升。新质生产力的讨论强调技术创新、要素组合和产业升级。':'Studies use different samples, outcomes and conditions. Task-level efficiency is not economic growth or demonstrated total-factor productivity growth. New quality productive forces concern innovation, factor coordination and industrial transformation.','可视化导论课程项目 · 数据访问于 2026.10.04':'Visualization course project · Sources accessed 2026.10.04','以证据观察，以交互理解。':'Observe through evidence. Understand through interaction.'
}};
const initialNodes=[];
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
while(walker.nextNode()){const node=walker.currentNode;if(!['SCRIPT','STYLE'].includes(node.parentElement?.tagName)){initialNodes.push({node,text:node.nodeValue});}}
const initialAttrs=[...document.querySelectorAll('[aria-label]')].map(node=>({node,text:node.getAttribute('aria-label')}));
I18N.applyStatic=()=>{initialNodes.forEach(({node,text})=>{if(!node.isConnected)return;const key=text.trim(),value=I18N.lang==='en'?I18N.staticText[key]:undefined;node.nodeValue=value?text.replace(key,value):text;});initialAttrs.forEach(({node,text})=>{const translated={ '章节导航':'Chapter navigation','选择趋势年份':'Trend range','AI 使用率折线图':'AI-adoption trend','AI 连接劳动者、劳动资料与劳动对象，促进要素协同':'AI connects workers, production tools and objects of work','行业选择':'Choose an industry' };node.setAttribute('aria-label',I18N.lang==='en'?(translated[text]||text):text);});document.documentElement.lang=I18N.lang==='en'?'en':'zh-CN';document.title=I18N.lang==='en'?'Intelligence in Motion · AI Productivity Observatory':'智变 · AI 新质生产力观察站';document.querySelector('#language').textContent=I18N.lang==='en'?'中文':'EN';document.querySelector('#language').setAttribute('aria-label',I18N.lang==='en'?'Switch to Chinese':'切换为英语');};
try{if(localStorage.getItem('ai-language')==='en')I18N.lang='en';}catch{}
document.querySelector('#language').addEventListener('click',()=>{I18N.lang=I18N.lang==='zh'?'en':'zh';try{localStorage.setItem('ai-language',I18N.lang);}catch{}I18N.applyStatic();window.dispatchEvent(new Event('languagechange'));});
I18N.applyStatic();
